import {
  MessageTemplateDefinition,
  MessageTemplateType,
} from './message-template.types';

export const MESSAGE_TEMPLATES: MessageTemplateDefinition[] = [
  {
    type: MessageTemplateType.LEAD_RESPONSE,
    label: 'Odpowiedź na lead',
    description: 'Pierwsza odpowiedź na zapytanie z publicznej strony oferty.',
    requiredContext: ['clientName', 'listingTitle'],
    subject: 'Re: {{listingTitle}}',
    body: [
      'Dzień dobry {{clientName}},',
      '',
      'dziękuję za zapytanie dotyczące oferty "{{listingTitle}}".',
      '{{leadReference}}',
      'Chętnie odpowiem na pytania i mogę zaproponować dogodny termin rozmowy albo prezentacji.',
      '',
      'Pozdrawiam,',
      '{{agentName}}',
      '{{agentContact}}',
    ].join('\n'),
  },
  {
    type: MessageTemplateType.APPOINTMENT_CONFIRMATION,
    label: 'Potwierdzenie spotkania',
    description: 'Krótkie potwierdzenie terminu spotkania lub prezentacji.',
    requiredContext: [
      'clientName',
      'listingTitle',
      'appointmentDate',
      'appointmentTime',
    ],
    subject: 'Potwierdzenie spotkania - {{listingTitle}}',
    body: [
      'Dzień dobry {{clientName}},',
      '',
      'potwierdzam spotkanie dotyczące oferty "{{listingTitle}}".',
      'Termin: {{appointmentDate}}, godz. {{appointmentTime}}.',
      'Miejsce: {{listingAddress}}.',
      '',
      'W razie potrzeby proszę o kontakt.',
      '',
      'Pozdrawiam,',
      '{{agentName}}',
      '{{agentContact}}',
    ].join('\n'),
  },
  {
    type: MessageTemplateType.VIEWING_FOLLOW_UP,
    label: 'Follow-up po prezentacji',
    description: 'Wiadomość po obejrzeniu nieruchomości przez klienta.',
    requiredContext: ['clientName', 'listingTitle'],
    subject: 'Podsumowanie prezentacji - {{listingTitle}}',
    body: [
      'Dzień dobry {{clientName}},',
      '',
      'dziękuję za udział w prezentacji oferty "{{listingTitle}}".',
      'Chętnie poznam Pani/Pana wrażenia i odpowiem na dodatkowe pytania.',
      '',
      'Jeśli oferta jest nadal interesująca, możemy omówić kolejne kroki.',
      '',
      'Pozdrawiam,',
      '{{agentName}}',
      '{{agentContact}}',
    ].join('\n'),
  },
  {
    type: MessageTemplateType.DOCUMENT_REQUEST,
    label: 'Prośba o dokumenty',
    description: 'Prośba o uzupełnienie dokumentów potrzebnych do obsługi.',
    requiredContext: ['clientName', 'listingTitle', 'documentList'],
    subject: 'Dokumenty do oferty - {{listingTitle}}',
    body: [
      'Dzień dobry {{clientName}},',
      '',
      'proszę o przesłanie dokumentów potrzebnych do dalszej obsługi oferty "{{listingTitle}}":',
      '{{documentList}}',
      '',
      'Po ich otrzymaniu zweryfikuję kompletność i wrócę z informacją o kolejnych krokach.',
      '',
      'Pozdrawiam,',
      '{{agentName}}',
      '{{agentContact}}',
    ].join('\n'),
  },
  {
    type: MessageTemplateType.PRICE_CHANGE,
    label: 'Informacja o zmianie ceny',
    description: 'Wiadomość do klienta o aktualizacji ceny oferty.',
    requiredContext: ['clientName', 'listingTitle', 'price'],
    subject: 'Aktualizacja ceny - {{listingTitle}}',
    body: [
      'Dzień dobry {{clientName}},',
      '',
      'informuję, że cena oferty "{{listingTitle}}" została zaktualizowana.',
      'Aktualna cena: {{price}}.',
      '{{previousPriceLine}}',
      '',
      'Jeśli chce Pani/Pan wrócić do rozmowy o tej nieruchomości, jestem do dyspozycji.',
      '',
      'Pozdrawiam,',
      '{{agentName}}',
      '{{agentContact}}',
    ].join('\n'),
  },
];
