export interface LocationCatalogEntry {
  id: string;
  name: string;
  municipality?: string;
  county: string;
  voivodeship: string;
  lat: number;
  lng: number;
  priority: number;
}

export const LOCATION_CATALOG: LocationCatalogEntry[] = [
  {
    id: 'pl-kujawsko-pomorskie-labiszyn',
    name: 'Łabiszyn',
    county: 'żniński',
    voivodeship: 'kujawsko-pomorskie',
    lat: 52.9521,
    lng: 17.9198,
    priority: 90,
  },
  {
    id: 'pl-kujawsko-pomorskie-bydgoszcz',
    name: 'Bydgoszcz',
    county: 'Bydgoszcz',
    voivodeship: 'kujawsko-pomorskie',
    lat: 53.1235,
    lng: 18.0084,
    priority: 100,
  },
  {
    id: 'pl-kujawsko-pomorskie-torun',
    name: 'Toruń',
    county: 'Toruń',
    voivodeship: 'kujawsko-pomorskie',
    lat: 53.0138,
    lng: 18.5984,
    priority: 100,
  },
  {
    id: 'pl-mazowieckie-warszawa',
    name: 'Warszawa',
    county: 'Warszawa',
    voivodeship: 'mazowieckie',
    lat: 52.2297,
    lng: 21.0122,
    priority: 100,
  },
  {
    id: 'pl-malopolskie-krakow',
    name: 'Kraków',
    county: 'Kraków',
    voivodeship: 'małopolskie',
    lat: 50.0647,
    lng: 19.945,
    priority: 100,
  },
  {
    id: 'pl-lodzkie-lodz',
    name: 'Łódź',
    county: 'Łódź',
    voivodeship: 'łódzkie',
    lat: 51.7592,
    lng: 19.456,
    priority: 100,
  },
  {
    id: 'pl-dolnoslaskie-wroclaw',
    name: 'Wrocław',
    county: 'Wrocław',
    voivodeship: 'dolnośląskie',
    lat: 51.1079,
    lng: 17.0385,
    priority: 100,
  },
  {
    id: 'pl-wielkopolskie-poznan',
    name: 'Poznań',
    county: 'Poznań',
    voivodeship: 'wielkopolskie',
    lat: 52.4064,
    lng: 16.9252,
    priority: 100,
  },
  {
    id: 'pl-pomorskie-gdansk',
    name: 'Gdańsk',
    county: 'Gdańsk',
    voivodeship: 'pomorskie',
    lat: 54.352,
    lng: 18.6466,
    priority: 100,
  },
  {
    id: 'pl-zachodniopomorskie-szczecin',
    name: 'Szczecin',
    county: 'Szczecin',
    voivodeship: 'zachodniopomorskie',
    lat: 53.4285,
    lng: 14.5528,
    priority: 100,
  },
  {
    id: 'pl-lubelskie-lublin',
    name: 'Lublin',
    county: 'Lublin',
    voivodeship: 'lubelskie',
    lat: 51.2465,
    lng: 22.5684,
    priority: 100,
  },
  {
    id: 'pl-podlaskie-bialystok',
    name: 'Białystok',
    county: 'Białystok',
    voivodeship: 'podlaskie',
    lat: 53.1325,
    lng: 23.1688,
    priority: 100,
  },
  {
    id: 'pl-slaskie-katowice',
    name: 'Katowice',
    county: 'Katowice',
    voivodeship: 'śląskie',
    lat: 50.2649,
    lng: 19.0238,
    priority: 100,
  },
  {
    id: 'pl-pomorskie-gdynia',
    name: 'Gdynia',
    county: 'Gdynia',
    voivodeship: 'pomorskie',
    lat: 54.5189,
    lng: 18.5305,
    priority: 95,
  },
  {
    id: 'pl-slaskie-czestochowa',
    name: 'Częstochowa',
    county: 'Częstochowa',
    voivodeship: 'śląskie',
    lat: 50.8118,
    lng: 19.1203,
    priority: 95,
  },
  {
    id: 'pl-mazowieckie-radom',
    name: 'Radom',
    county: 'Radom',
    voivodeship: 'mazowieckie',
    lat: 51.4027,
    lng: 21.1471,
    priority: 95,
  },
  {
    id: 'pl-swietokrzyskie-kielce',
    name: 'Kielce',
    county: 'Kielce',
    voivodeship: 'świętokrzyskie',
    lat: 50.8661,
    lng: 20.6286,
    priority: 95,
  },
  {
    id: 'pl-podkarpackie-rzeszow',
    name: 'Rzeszów',
    county: 'Rzeszów',
    voivodeship: 'podkarpackie',
    lat: 50.0413,
    lng: 21.999,
    priority: 95,
  },
  {
    id: 'pl-warminsko-mazurskie-olsztyn',
    name: 'Olsztyn',
    county: 'Olsztyn',
    voivodeship: 'warmińsko-mazurskie',
    lat: 53.7784,
    lng: 20.4801,
    priority: 95,
  },
  {
    id: 'pl-opolskie-opole',
    name: 'Opole',
    county: 'Opole',
    voivodeship: 'opolskie',
    lat: 50.6751,
    lng: 17.9213,
    priority: 95,
  },
  {
    id: 'pl-lubuskie-zielona-gora',
    name: 'Zielona Góra',
    county: 'Zielona Góra',
    voivodeship: 'lubuskie',
    lat: 51.9356,
    lng: 15.5062,
    priority: 95,
  },
  {
    id: 'pl-lubuskie-gorzow-wielkopolski',
    name: 'Gorzów Wielkopolski',
    county: 'Gorzów Wielkopolski',
    voivodeship: 'lubuskie',
    lat: 52.7368,
    lng: 15.2288,
    priority: 95,
  },
];
